language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - "sudo apt-get install alien"
    - "alien -i oracle-instantclient-basic-10.2.0.5-1.i386.rpm"
    - "alien -i oracle-instantclient-devel-10.2.0.5-1.i386.rpm"
    - "alien -i oracle-instantclient-basic-10.2.0.5-1.x86_64.rpm"
    - "alien -i oracle-instantclient-devel-10.2.0.5-1.x86_64.rpm"
    - "sudo apt-get install wget"
    - "sudo apt-get install python-setuptools"
    - "sudo apt-get install python-virtualenv"
    - "sudo easy_install pip"
    - "virtualenv venv"
    - "ls"
    - "source venv/bin/activate"
install:
    - "pip install -r requirements.txt"
script: 
    - "sh init.sh"
    - "python manage.py test"
